import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { DEFAULT_CANDIDATE_DIRS } from './binaries.js';

// "Launch Desk Agent when phone is docked" (Device pane). The trigger has to
// live OUTSIDE the Electron process -- the whole point is launching it when
// it's NOT running yet -- so this installs a user-domain launchd LaunchAgent
// that blocks on `adb wait-for-device` (event-driven, no polling interval,
// near-zero idle CPU) rather than polling `adb devices` on a timer.
const LABEL = 'com.deskagent.dockwatch';
const BUNDLE_ID = 'com.deskagent.mac';

export function scriptPath(homeDir: string = os.homedir()): string {
  return path.join(homeDir, 'Library', 'Application Support', 'Desk Agent', 'dock-watch.sh');
}

export function plistPath(homeDir: string = os.homedir()): string {
  return path.join(homeDir, 'Library', 'LaunchAgents', `${LABEL}.plist`);
}

export function logPath(homeDir: string = os.homedir()): string {
  return path.join(homeDir, 'Library', 'Logs', 'Desk Agent', 'dock-watch.log');
}

function domainTarget(): string {
  return `gui/${process.getuid?.() ?? 0}`;
}

function serviceTarget(): string {
  return `${domainTarget()}/${LABEL}`;
}

// Generates the watcher's shell script body. After launching/focusing the
// app it blocks on `adb wait-for-disconnect` before exiting -- without that
// second wait, launchd's KeepAlive would restart `wait-for-device`
// immediately while the phone is STILL attached, re-opening/refocusing the
// app in a tight loop for as long as it stays docked. `open -b` on an
// already-running app (Electron's single-instance lock guarantees there's
// at most one) just focuses it, it does not spawn a second instance.
export function buildWatchScript(candidateDirs: string[] = DEFAULT_CANDIDATE_DIRS): string {
  const dirChecks = candidateDirs.map((dir) => `if [ -z "$ADB" ] && [ -x "${dir}/adb" ]; then ADB="${dir}/adb"; fi`).join('\n');
  return `#!/bin/sh
# Generated by Desk Agent (apps/mac/src/main/dockWatch.ts) -- regenerated
# every time "Launch Desk Agent when phone is docked" is toggled on. Do not
# edit by hand, it will be overwritten.
ADB=""
${dirChecks}
if [ -z "$ADB" ]; then
  ADB=$(command -v adb 2>/dev/null || true)
fi
if [ -z "$ADB" ]; then
  echo "dock-watch: adb not found in any known location, giving up for this run" >&2
  exit 1
fi

"$ADB" wait-for-device
open -b ${BUNDLE_ID}
"$ADB" wait-for-disconnect
`;
}

// launchd's default ThrottleInterval (10s) is the safety net if adb is ever
// unresolvable and the script above exits immediately every time --
// KeepAlive would otherwise respawn it in a tight loop.
export function buildPlist(watchScriptPath: string, watchLogPath: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${watchScriptPath}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${watchLogPath}</string>
  <key>StandardErrorPath</key>
  <string>${watchLogPath}</string>
</dict>
</plist>
`;
}

export function isInstalled(homeDir: string = os.homedir()): boolean {
  return fs.existsSync(plistPath(homeDir));
}

export interface DockWatchDeps {
  /** Injectable for testing -- never invoke a real launchctl from a test. */
  runLaunchctl?: (args: string[]) => void;
  homeDir?: string;
}

function defaultRunLaunchctl(args: string[]): void {
  execFileSync('launchctl', args);
}

// Writes the script + plist and loads it via launchctl, then returns the
// actual resulting state (isInstalled(), not an assumed success) -- same
// read-back-the-real-state pattern as login:setLaunchAtLogin, since
// launchctl can fail silently from this caller's perspective too.
export function install(deps: DockWatchDeps = {}): boolean {
  const homeDir = deps.homeDir ?? os.homedir();
  const runLaunchctl = deps.runLaunchctl ?? defaultRunLaunchctl;
  const watchScriptPath = scriptPath(homeDir);
  const watchPlistPath = plistPath(homeDir);
  const watchLogPath = logPath(homeDir);

  fs.mkdirSync(path.dirname(watchScriptPath), { recursive: true });
  fs.mkdirSync(path.dirname(watchLogPath), { recursive: true });
  fs.mkdirSync(path.dirname(watchPlistPath), { recursive: true });
  fs.writeFileSync(watchScriptPath, buildWatchScript());
  fs.chmodSync(watchScriptPath, 0o755);
  fs.writeFileSync(watchPlistPath, buildPlist(watchScriptPath, watchLogPath));

  // bootout first (ignoring failure -- fine if nothing was loaded yet), then
  // bootstrap fresh, so re-enabling after a prior install never hits "service
  // already loaded" and silently leaves an old script/plist active underneath.
  try {
    runLaunchctl(['bootout', serviceTarget()]);
  } catch {
    // Wasn't loaded -- expected on first install.
  }
  try {
    runLaunchctl(['bootstrap', domainTarget(), watchPlistPath]);
  } catch {
    // isInstalled() below reflects reality either way (plist may be written
    // but not actually loaded) -- the caller trusts that return value, not
    // this call's success.
  }

  return isInstalled(homeDir);
}

export function uninstall(deps: DockWatchDeps = {}): boolean {
  const homeDir = deps.homeDir ?? os.homedir();
  const runLaunchctl = deps.runLaunchctl ?? defaultRunLaunchctl;
  const watchPlistPath = plistPath(homeDir);

  try {
    runLaunchctl(['bootout', serviceTarget()]);
  } catch {
    // Already not loaded -- fine, still remove the plist below.
  }
  if (fs.existsSync(watchPlistPath)) fs.rmSync(watchPlistPath);

  return isInstalled(homeDir);
}
